M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Thu 22 Sep 2022 10:40:44 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-22T10:40:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.99Y-4.81
T0
M30
